var CODE = {};
var keyCodes = {};

(function() {
  var keymap = {
  // from keyboard.c
  SPECIAL_KEY_MOD : [0xfe, 'mod'],
  SPECIAL_KEY_BENCHMARK : [0xfd, 'bench'],

  // from
  // https://github.com/hathach/tinyusb/blob/master/src/class/hid/hid.h
  // https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values
  // https://keycode.info/
  HID_KEY_NONE : [0x00, ' ', 0],
  HID_KEY_A : [0x04, 'a', "KeyA"],
  HID_KEY_B : [0x05, 'b', "KeyB"],
  HID_KEY_C : [0x06, 'c', "KeyC"],
  HID_KEY_D : [0x07, 'd', "KeyD"],
  HID_KEY_E : [0x08, 'e', "KeyE"],
  HID_KEY_F : [0x09, 'f', "KeyF"],
  HID_KEY_G : [0x0A, 'g', "KeyG"],
  HID_KEY_H : [0x0B, 'h', "KeyH"],
  HID_KEY_I : [0x0C, 'i', "KeyI"],
  HID_KEY_J : [0x0D, 'j', "KeyJ"],
  HID_KEY_K : [0x0E, 'k', "KeyK"],
  HID_KEY_L : [0x0F, 'l', "KeyL"],
  HID_KEY_M : [0x10, 'm', "KeyM"],
  HID_KEY_N : [0x11, 'n', "KeyN"],
  HID_KEY_O : [0x12, 'o', "KeyO"],
  HID_KEY_P : [0x13, 'p', "KeyP"],
  HID_KEY_Q : [0x14, 'q', "KeyQ"],
  HID_KEY_R : [0x15, 'r', "KeyR"],
  HID_KEY_S : [0x16, 's', "KeyS"],
  HID_KEY_T : [0x17, 't', "KeyT"],
  HID_KEY_U : [0x18, 'u', "KeyU"],
  HID_KEY_V : [0x19, 'v', "KeyV"],
  HID_KEY_W : [0x1A, 'w', "KeyW"],
  HID_KEY_X : [0x1B, 'x', "KeyX"],
  HID_KEY_Y : [0x1C, 'y', "KeyY"],
  HID_KEY_Z : [0x1D, 'z', "KeyZ"],
  HID_KEY_1 : [0x1E, '1', "Digit1"],
  HID_KEY_2 : [0x1F, '2', "Digit2"],
  HID_KEY_3 : [0x20, '3', "Digit3"],
  HID_KEY_4 : [0x21, '4', "Digit4"],
  HID_KEY_5 : [0x22, '5', "Digit5"],
  HID_KEY_6 : [0x23, '6', "Digit6"],
  HID_KEY_7 : [0x24, '7', "Digit7"],
  HID_KEY_8 : [0x25, '8', "Digit8"],
  HID_KEY_9 : [0x26, '9', "Digit9"],
  HID_KEY_0 : [0x27, '0', "Digit0"],
  HID_KEY_ENTER : [0x28, 'enter', "Enter"],
  HID_KEY_ESCAPE : [0x29, 'esc', "Escape"],
  HID_KEY_BACKSPACE : [0x2A, 'bksp', "Backspace"],
  HID_KEY_TAB : [0x2B, 'tab', "Tab"],
  HID_KEY_SPACE : [0x2C, 'space', "Space"],
  HID_KEY_MINUS : [0x2D, '-', "Minus"],
  HID_KEY_EQUAL : [0x2E, '=', "Equal"],
  HID_KEY_BRACKET_LEFT : [0x2F, '[', "BracketLeft"],
  HID_KEY_BRACKET_RIGHT : [0x30, ']', "BracketRight"],
  HID_KEY_BACKSLASH : [0x31, '\\', "Backslash"],
  HID_KEY_EUROPE_1 : [0x32, ''],
  HID_KEY_SEMICOLON : [0x33, ';', "Semicolon"],
  HID_KEY_APOSTROPHE : [0x34, '\'', "Quote"],
  HID_KEY_GRAVE : [0x35, '~', "Backquote"], // display as tilde because it's clearer
  HID_KEY_COMMA : [0x36, ',', "Comma"],
  HID_KEY_PERIOD : [0x37, '.', "Period"],
  HID_KEY_SLASH : [0x38, '/', "Slash"],
  HID_KEY_CAPS_LOCK : [0x39, 'caps', "CapsLock"],
  HID_KEY_F1 : [0x3A, 'f1', "F1"],
  HID_KEY_F2 : [0x3B, 'f2', "F2"],
  HID_KEY_F3 : [0x3C, 'f3', "F3"],
  HID_KEY_F4 : [0x3D, 'f4', "F4"],
  HID_KEY_F5 : [0x3E, 'f5', "F5"],
  HID_KEY_F6 : [0x3F, 'f6', "F6"],
  HID_KEY_F7 : [0x40, 'f7', "F7"],
  HID_KEY_F8 : [0x41, 'f8', "F8"],
  HID_KEY_F9 : [0x42, 'f9', "F9"],
  HID_KEY_F10 : [0x43, 'f10', "F10"],
  HID_KEY_F11 : [0x44, 'f11', "F11"],
  HID_KEY_F12 : [0x45, 'f12', "F12"],
  HID_KEY_PRINT_SCREEN : [0x46, 'prtSn', "PrintScreen"],
  HID_KEY_SCROLL_LOCK : [0x47, 'sclLk', "ScrollLock"],
  HID_KEY_PAUSE : [0x48, 'pause', "Pause"],
  HID_KEY_INSERT : [0x49, 'ins', "Insert"],
  HID_KEY_HOME : [0x4A, 'home', "Home"],
  HID_KEY_PAGE_UP : [0x4B, 'pgup', "PageUp"],
  HID_KEY_DELETE : [0x4C, 'del', "Delete"],
  HID_KEY_END : [0x4D, 'end', "End"],
  HID_KEY_PAGE_DOWN : [0x4E, 'pgdn', "PageDown"],
  HID_KEY_ARROW_RIGHT : [0x4F, '&rarr;', "ArrowRight"],
  HID_KEY_ARROW_LEFT : [0x50, '&larr;', "ArrowLeft"],
  HID_KEY_ARROW_DOWN : [0x51, '&darr;', "ArrowDown"],
  HID_KEY_ARROW_UP : [0x52, '&uarr;', "ArrowUp"],
  HID_KEY_NUM_LOCK : [0x53, 'numlk', "Numlock"],
  HID_KEY_KEYPAD_DIVIDE : [0x54, 'kp /', "NumpadDivide"],
  HID_KEY_KEYPAD_MULTIPLY : [0x55, 'kp *', "NumpadMultiply"],
  HID_KEY_KEYPAD_SUBTRACT : [0x56, 'kp -', "NumpadSubtract"],
  HID_KEY_KEYPAD_ADD : [0x57, 'kp +', "NumpadAdd"],
  HID_KEY_KEYPAD_ENTER : [0x58, 'kp ent', "NumpadEnter"],
  HID_KEY_KEYPAD_1 : [0x59, 'kp 1', "Numpad1"],
  HID_KEY_KEYPAD_2 : [0x5A, 'kp 2', "Numpad2"],
  HID_KEY_KEYPAD_3 : [0x5B, 'kp 3', "Numpad3"],
  HID_KEY_KEYPAD_4 : [0x5C, 'kp 4', "Numpad4"],
  HID_KEY_KEYPAD_5 : [0x5D, 'kp 5', "Numpad5"],
  HID_KEY_KEYPAD_6 : [0x5E, 'kp 6', "Numpad6"],
  HID_KEY_KEYPAD_7 : [0x5F, 'kp 7', "Numpad7"],
  HID_KEY_KEYPAD_8 : [0x60, 'kp 8', "Numpad8"],
  HID_KEY_KEYPAD_9 : [0x61, 'kp 9', "Numpad9"],
  HID_KEY_KEYPAD_0 : [0x62, 'kp 0', "Numpad0"],
  HID_KEY_KEYPAD_DECIMAL : [0x63, 'kp .', "NumpadDecimal"],
  HID_KEY_EUROPE_2 : [0x64, '2'],
  HID_KEY_APPLICATION : [0x65, 'app'],
  HID_KEY_POWER : [0x66, 'power', "Power"],
  HID_KEY_KEYPAD_EQUAL : [0x67, 'kp ='],
  HID_KEY_F13 : [0x68, 'f13', "F13"],
  HID_KEY_F14 : [0x69, 'f14', "F14"],
  HID_KEY_F15 : [0x6A, 'f15', "F15"],
  HID_KEY_F16 : [0x6B, 'f16', "F16"],
  HID_KEY_F17 : [0x6C, 'f17', "F17"],
  HID_KEY_F18 : [0x6D, 'f18', "F18"],
  HID_KEY_F19 : [0x6E, 'f19', "F19"],
  HID_KEY_F20 : [0x6F, 'f20', "F20"],
  HID_KEY_F21 : [0x70, 'f21', "F21"],
  HID_KEY_F22 : [0x71, 'f22', "F22"],
  HID_KEY_F23 : [0x72, 'f23', "F23"],
  HID_KEY_F24 : [0x73, 'f24', "F24"],
  HID_KEY_EXECUTE : [0x74, 'exec'],
  HID_KEY_HELP : [0x75, 'help', "Help"],
  HID_KEY_MENU : [0x76, 'menu', "ContextMenu"],
  HID_KEY_SELECT : [0x77, 'sel'],
  HID_KEY_STOP : [0x78, 'stop'],
  HID_KEY_AGAIN : [0x79, 'again'],
  HID_KEY_UNDO : [0x7A, 'undo', "Undo"],
  HID_KEY_CUT : [0x7B, 'cut', "Cut"],
  HID_KEY_COPY : [0x7C, 'copy', "Copy"],
  HID_KEY_PASTE : [0x7D, 'paste', "Paste"],
  HID_KEY_FIND : [0x7E, 'find', "Find"],
  HID_KEY_MUTE : [0x7F, 'mute', "AudioVolumeMute"],
  HID_KEY_VOLUME_UP : [0x80, 'vol up', "AudioVolumeUp"],
  HID_KEY_VOLUME_DOWN : [0x81, 'vol dn', "AudioVolumeDown"],
  HID_KEY_LOCKING_CAPS_LOCK : [0x82, ''],
  HID_KEY_LOCKING_NUM_LOCK : [0x83, ''],
  HID_KEY_LOCKING_SCROLL_LOCK : [0x84, ''],
  HID_KEY_KEYPAD_COMMA : [0x85, 'kp ,', "NumpadComma"],
  HID_KEY_KEYPAD_EQUAL_SIGN : [0x86, 'kp =', "NumpadEqual"],
  HID_KEY_KANJI1 : [0x87, 'KJ1'],
  HID_KEY_KANJI2 : [0x88, 'KJ2'],
  HID_KEY_KANJI3 : [0x89, 'KJ3'],
  HID_KEY_KANJI4 : [0x8A, 'KJ4'],
  HID_KEY_KANJI5 : [0x8B, 'KJ5'],
  HID_KEY_KANJI6 : [0x8C, 'KJ6'],
  HID_KEY_KANJI7 : [0x8D, 'KJ7'],
  HID_KEY_KANJI8 : [0x8E, 'KJ8'],
  HID_KEY_KANJI9 : [0x8F, 'KJ9'],
  HID_KEY_LANG1 : [0x90, 'lang1'],
  HID_KEY_LANG2 : [0x91, 'lang2'],
  HID_KEY_LANG3 : [0x92, 'lang3'],
  HID_KEY_LANG4 : [0x93, 'lang4'],
  HID_KEY_LANG5 : [0x94, 'lang5'],
  HID_KEY_LANG6 : [0x95, 'lang6'],
  HID_KEY_LANG7 : [0x96, 'lang7'],
  HID_KEY_LANG8 : [0x97, 'lang8'],
  HID_KEY_LANG9 : [0x98, 'lang9'],
  HID_KEY_ALTERNATE_ERASE : [0x99, ''],
  HID_KEY_SYSREQ_ATTENTION : [0x9A, ''],
  HID_KEY_CANCEL : [0x9B, 'cancel', "Cancel"],
  HID_KEY_CLEAR : [0x9C, 'clear'],
  HID_KEY_PRIOR : [0x9D, 'prior'],
  HID_KEY_RETURN : [0x9E, 'ret'],
  HID_KEY_SEPARATOR : [0x9F, 'sep'],
  HID_KEY_OUT : [0xA0, 'out'],
  HID_KEY_OPER : [0xA1, 'oper'],
  HID_KEY_CLEAR_AGAIN : [0xA2, ''],
  HID_KEY_CRSEL_PROPS : [0xA3, ''],
  HID_KEY_EXSEL : [0xA4, ''],
  // RESERVED					 : [0xA5-DF, ''],
  HID_KEY_CONTROL_LEFT : [0xE0, 'ctrl', "ControlLeft"],
  HID_KEY_SHIFT_LEFT : [0xE1, 'shift', "ShiftLeft"],
  HID_KEY_ALT_LEFT : [0xE2, 'alt', "AltLeft"],
  HID_KEY_GUI_LEFT : [0xE3, 'gui', "MetaLeft"],
  HID_KEY_CONTROL_RIGHT : [0xE4, 'ctrl right', "ControlRight"],
  HID_KEY_SHIFT_RIGHT : [0xE5, 'shift right', "ShiftRight"],
  HID_KEY_ALT_RIGHT : [0xE6, 'alt right', "AltRight"],
  HID_KEY_GUI_RIGHT : [0xE7, 'gui right', "MetaRight"],
};

CODE.NAME = {};
CODE.FROM_JS = {};
CODE.KEYMAPS ={};
keyCodes = keymap;

for (const [k, v] of Object.entries(keymap)) {
  CODE.NAME[v[0]] = k;
  CODE[k] = v[0];
  CODE.FROM_JS[v[2]] = v[0];
  
};
}());